apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          {
            "name": "ovs-net",
            "ips":  ["10.10.0.5/24"]
          }
]'
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: default-conf
          mountPath: /etc/nginx/conf.d/default.conf
      volumes:
      - name: default-conf
        hostPath:
          # Modify the path
          path: /home/alan/work/SDN-firewall/example/nginx/default.conf
          type: FileOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort
  selector:
    app: nginx
  externalTrafficPolicy: Local
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - name: port80
      port: 80
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30080
