apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  labels:
    app: network-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-tester
  template:
    metadata:
      labels:
        app: network-tester
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          {
            "name": "ovs-net",
            "ips":  ["10.10.0.1/24"]
          }
]'
    spec:
      containers:
      - name: network-tester #busybox
        image: alan0415/network-tester:alpine314 #busybox:latest
        command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000
