apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: python-alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-alpine
  template:
    metadata:
      labels:
        app: python-alpine
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          {
            "name": "ovs-net",
            "ips":  ["10.10.0.7/24"]
          }
]'
    spec:
      containers:
      - name: network-tester #busybox2
        image: alan0415/network-tester:alpine314 #busybox:latest
        command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: user-svc
#spec:
#  type: NodePort
#  selector:
#    app: python-alpine
#  externalTrafficPolicy: Local
#  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
#    - name: port8000
#      port: 8000
#      targetPort: 8000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
#      nodePort: 30081
