From python:3.8-slim
WORKDIR /app
RUN apt update
RUN apt install curl net-tools -y
COPY requirements.txt .
COPY main.py .
RUN pip3 install -r requirements.txt
CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
